[package]
name = "xx-core"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4", features = ["std"] }
ctor = "0.2"
enumflags2 = "0.7.8"
memchr = "2.6.4"
fmt = "0.1.0"
concat-idents = "1.1.5"
num-derive = "0.4.1"
num-traits = "0.2.17"
xx-core-macros = { path = "macros" }
