[package]
name = "xx-core-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
proc-macro2 = "1.0.67"
quote = "1.0.33"
syn = { version = "2.0.37", features = ["full", "visit-mut"] }

[lib]
proc-macro = true
